apiVersion: v1
kind: Secret
metadata:
  name: k8net-dev-secrets
  namespace: dev
type: kubernetes.io/tls
data:
  server.crt: |
       <crt contents here>
  server.key: |
       <private key contents here>