apiVersion: v1
kind: Secret
metadata:
  name: k8net-prod-secrets
  namespace: prod
type: kubernetes.io/tls
data:
  server.crt: |
       <crt contents here>
  server.key: |
       <private key contents here>