apiVersion: v1
kind: Secret
data:
  tls.crt: {{ .Values.api.secretCert }}
  tls.key: {{ .Values.api.secretKey }}
metadata:
  name: {{ include "dev-helm.fullname" . }}-tls
  labels: {{- include "dev-helm.labels" . | nindent 4 }}
type: kubernetes.io/tls